export const LOAD_MARKETS_SUCCESS = 'LOAD_MARKETS_SUCCESS';
export const CREATE_MARKET_SUCCESS = 'CREATE_MARKET_SUCCESS';

export const LOAD_CATEGORY_SUCCESS = 'LOAD_CATEGORY_SUCCESS';

export const FIREBASE_INIT = 'FIREBASE_INIT';
export const LOAD_STORE_SUCCESS = 'LOAD_STORE_SUCCESS';