export const FIND_SHOP_SUCCESS = 'FIND_SHOP_SUCCESS';
export const ADD_SHOP_HISTORY = 'ADD_SHOP_HISTORY';
export const DELETE_HISTORY_SHOP = 'DELETE_HISTORY_SHOP';
export const ADD_SHOP_FAVORITE = 'ADD_SHOP_FAVORITE';
export const DELETE_FAVORITE_SHOP = 'DELETE_FAVORITE_SHOP';
export const UPDATE_MY_SHOPS = 'UPDATE_MY_SHOPS';